### ISSUE TITLE
not working in ubuntu

### ISSUE THREAD

**Issue by krishnakulkarni88** [nathanprins/ESP32-IDF-WiFiManager#1]
i have put your files into a folder called main then i created cmakelists.txt file and make file by setting path as main and your file name,when i opened the terminal and run make menuconfig it is showing me
mongoose.h: No such file or directory
compilation terminated.
/home/unio/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'wifimanager.o' failed
make[1]: *** [wifimanager.o] Error 1
/home/unio/esp/esp-idf/make/project.mk:481: recipe for target 'component-main-build' failed
make: *** [component-main-build] Error 2

**Comment by nathanprins** [comment]
Yes, currently this library still requires you to manually add the [Mongoose networking library's source files](https://github.com/cesanta/mongoose) to the same folder. But I have to warn you: the version in this repository isn't up to date and I have since abandoned the project since I switched to [Mongoose OS](https://github.com/cesanta/mongoose-os) and I have no need for it anymore.
